// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mr_Robot.Data;

#nullable disable

namespace Mr_Robot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240531101121_AddSeasonToEpisodes")]
    partial class AddSeasonToEpisodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Mr_Robot.Models.EpisodesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OriginalAirDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<double>("USViewersMillions")
                        .HasColumnType("REAL");

                    b.Property<string>("WrittenBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("seasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("seasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Mr_Robot.Models.SeasonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstAired")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAired")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Mr_Robot.Models.EpisodesModel", b =>
                {
                    b.HasOne("Mr_Robot.Models.SeasonModel", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("seasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Mr_Robot.Models.SeasonModel", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
